# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Party.destroy_all
Guest.destroy_all


Party.create(party_name: "Buch")
Party.create(party_name: "Lichter")
Party.create(party_name: "Goodman")
Party.create(party_name: "Buch-Roger")
Party.create(party_name: "Goodman-John")
Party.create(party_name: "Goodman-Paul")
Party.create(party_name: "Speck")
Party.create(party_name: "Crowe")
Party.create(party_name: "Bennett")
Party.create(party_name: "Wells")
Party.create(party_name: "Wells-Chris")
Party.create(party_name: "Philip")
Party.create(party_name: "Philip-Josh")
Party.create(party_name: "Boyer")
Party.create(party_name: "GOP")
Party.create(party_name: "Ingley")
Party.create(party_name: "Mones")
Party.create(party_name: "McNulty")
Party.create(party_name: "Moroney")
Party.create(party_name: "Moroney-Eric")
Party.create(party_name: "Moroney-Eli")
Party.create(party_name: "Moroney-Sam")
Party.create(party_name: "Moroney-Sandy")
Party.create(party_name: "Moroney-Tina")
Party.create(party_name: "Mitropoulos")
Party.create(party_name: "Erickson")
Party.create(party_name: "Erickson-Barbara")
Party.create(party_name: "Erickson-Tom")
Party.create(party_name: "Pettengill")
Party.create(party_name: "Boyajian")
Party.create(party_name: "Brewster")
Party.create(party_name: "Rand")
Party.create(party_name: "Korshin")
Party.create(party_name: "Ayres")
Party.create(party_name: "Doucette")
Party.create(party_name: "Cook-Wilson")
Party.create(party_name: "Hanscom")
Party.create(party_name: "Heus")
Party.create(party_name: "Katsuta")
Party.create(party_name: "Mulcrone")
Party.create(party_name: "Cutler")
Party.create(party_name: "Sheridan")
Party.create(party_name: "Davis")
Party.create(party_name: "Munson")
Party.create(party_name: "Gordon")
Party.create(party_name: "Campanella")
Party.create(party_name: "Morrell")
Party.create(party_name: "Munschauer")
Party.create(party_name: "Tracy")
Party.create(party_name: "Fried")
Party.create(party_name: "Millarhouse")
Party.create(party_name: "Mandeville")
Party.create(party_name: "Hulnick")
Party.create(party_name: "Huffaker")
Party.create(party_name: "Sullivan")
Party.create(party_name: "Hawkins")
Party.create(party_name: "Shults")
Party.create(party_name: "Kisner")
Party.create(party_name: "Haynes")
Party.create(party_name: "Novak")
Party.create(party_name: "Schopke")
Party.create(party_name: "Sholl")
Party.create(party_name: "Ducommun")
Party.create(party_name: "Palanza")
Party.create(party_name: "Scotti")
Party.create(party_name: "Welles")
Party.create(party_name: "Whalen")
Party.create(party_name: "Fesette")
Party.create(party_name: "Racine")
Party.create(party_name: "Christ")
Party.create(party_name: "Breslin")
Party.create(party_name: "Kamer")
Party.create(party_name: "Klement")
Party.create(party_name: "Valeiras")
Party.create(party_name: "Marker")
Party.create(party_name: "Eichenfield")
Party.create(party_name: "Good")
Party.create(party_name: "Griswold")
Party.create(party_name: "Doucette-Liz")
Party.create(party_name: "Blank")
Party.create(party_name: "Gonzalez")
Party.create(party_name: "Boutelle")
Party.create(party_name: "Teuscher")
Party.create(party_name: "Rhea")
Party.create(party_name: "Markham")
Party.create(party_name: "Nauleau")
Party.create(party_name: "Reisman")
Party.create(party_name: "Clements")
Party.create(party_name: "Clements-Becky")
Party.create(party_name: "Mayor")
Party.create(party_name: "Root")
Party.create(party_name: "Smith")

Guest.create(first_name: "Brian", last_name: "Buch", email: "brianpbuch@gmail.com", party_id:1, meal_id:1)
Guest.create(first_name:"Britt", last_name:"Berger", email: "brittberger@gmail.com", party_id:1,meal_id:1)
Guest.create(first_name:"Karen", last_name:"Buch", email: "karen.buch@gmail.com", party_id:2,meal_id:1)
Guest.create(first_name:"Rob", last_name:"Lichter", email: "robert.lichter@gmail.com", party_id:2,meal_id:1)
Guest.create(first_name:"Susan", last_name:"Goodman", email: "susangoodman1@verizon.net", party_id:5,meal_id:1)
Guest.create(first_name:"John", last_name:"Goodman", email: "", party_id:5,meal_id:1)
Guest.create(first_name:"Roger", last_name:"Buch", email: "rogerbuch@ymail.com", party_id:4,meal_id:1)
Guest.create(first_name:"Sarah", last_name:"Thiemann", email: "sjtmann@hotmail.com", party_id:4,meal_id:1)
Guest.create(first_name:"Paul", last_name:"Goodman", email: "", party_id:6,meal_id:1)
Guest.create(first_name:"Scott", last_name:"Goodman", email: "vtgoodman@gmail.com", party_id:3,meal_id:1)
Guest.create(first_name:"Emily", last_name:"Goodman", email: "vtgoodman@gmail.com", party_id:3,meal_id:1)
Guest.create(first_name:"Molly", last_name:"Goodman", email: "fake", party_id:3,meal_id:1)
Guest.create(first_name:"Bryson", last_name:"Goodman",email: "fake", party_id:3,meal_id:1)
Guest.create(first_name:"Brett", last_name:"Goodman",email: "fake",  party_id:3,meal_id:1)
Guest.create(first_name:"Paul", last_name:"Goodman", email: "", party_id:6,meal_id:1)
Guest.create(first_name:"Shauna", last_name:"Goodman", email: "shaunagoodman@verizon.net", party_id:6,meal_id:1)
Guest.create(first_name:"Delaney", last_name:"Goodman", email: "", party_id:6,meal_id:1)
Guest.create(first_name:"Tabitha", last_name:"Goodman", email: "", party_id:6,meal_id:1)
Guest.create(first_name:"Shane", last_name:"Goodman",email: "", party_id:6,meal_id:1)
Guest.create(first_name:"Sally", last_name:"Speck", email: "sastspeck@aol.com", party_id:7,meal_id:1)
Guest.create(first_name:"Stefan", last_name:"Speck", email: "sastspeck@aol.com", party_id:7,meal_id:1)
Guest.create(first_name:"Kaelen", last_name:"Speck",email: "", party_id:7,meal_id:1)
Guest.create(first_name:"Braden", last_name:"Speck",email: "", party_id:7,meal_id:1)
Guest.create(first_name:"Katy", last_name:"Crowe", email: "goodmankaty@gmail.com", party_id:8,meal_id:1)
Guest.create(first_name:"Jeff", last_name:"Crowe", email: "", party_id:8,meal_id:1)
Guest.create(first_name:"Stacy", last_name:"Bennett", email: "stacylwells@gmail.com", party_id:9,meal_id:1)
Guest.create(first_name:"Chad", last_name:"Bennett", email: "", party_id:9,meal_id:1)
Guest.create(first_name:"Emmy", last_name:"Bennett", email: "", party_id:9,meal_id:1)
Guest.create(first_name:"Lucy", last_name:"Wells", email: "LucyW1215@gmail.com", party_id:10,meal_id:1)
Guest.create(first_name:"Mike", last_name:"Wells", email: "MichaelLWells11@gmail.com", party_id:10,meal_id:1)
Guest.create(first_name:"Chris", last_name:"Wells", email: "ckwells528@gmail.com", party_id:11,meal_id:1)
Guest.create(first_name:"Amber", last_name:"Wells", email: "ambryt110@gmail.com", party_id:11,meal_id:1)
Guest.create(first_name:"Quentin", last_name:"Wells", email: "",party_id:11,meal_id:1)
Guest.create(first_name:"Elyana", last_name:"Wells", email: "",party_id:11,meal_id:1)
Guest.create(first_name:"Deb", last_name:"Philip", email: "dphilip39@comcast.net", party_id:12,meal_id:1)
Guest.create(first_name:"Don", last_name:"Philip", email: "", party_id:12,meal_id:1)
Guest.create(first_name:"Josh", last_name:"Philip", email: "", party_id:13,meal_id:1)
Guest.create(first_name:"Amanda", last_name:"Mones", email: "", party_id:16,meal_id:1)
Guest.create(first_name:"Dan", last_name:"Mones", email: "", party_id:16,meal_id:1)
Guest.create(first_name:"Asher", last_name:"Mones", email: "",party_id:16,meal_id:1)
Guest.create(first_name:"Joni", last_name:"Philip", email: "djphilip8@gmail.om", party_id:14,meal_id:1)
Guest.create(first_name:"Dave", last_name:"Boyer", email: "", party_id:14,meal_id:1)
Guest.create(first_name:"Danielle", last_name:"Ingley", email: "", party_id:15,meal_id:1)
Guest.create(first_name:"Jason", last_name:"Ingley", email: "", party_id:15,meal_id:1)
Guest.create(first_name:"Mikayla", last_name:"Ingley", email: "", party_id:15,meal_id:1)
Guest.create(first_name:"Arabella", last_name:"Ingley", email: "", party_id:15,meal_id:1)
Guest.create(first_name:"Sean", last_name:"McNulty", email: "", party_id:17,meal_id:1)
Guest.create(first_name:"Ali", last_name:"McNulty", email: "", party_id:17,meal_id:1)
Guest.create(first_name:"Jean", last_name:"Moroney", email: "jamoroney99@gmail.com", party_id:18,meal_id:1)
Guest.create(first_name:"Paul", last_name:"Moroney", email: "pmoroney99@gmail.com", party_id:18,meal_id:1)
Guest.create(first_name:"Eric", last_name:"Moroney", email: "epmoroney@sbcglobal.net", party_id:19,meal_id:1)
Guest.create(first_name:"Elizabeth", last_name:"Moroney", email: "eli.moroney@gmail.com", party_id:20,meal_id:1)
Guest.create(first_name:"Samantha", last_name:"Moroney", email: "sfmoroney@gmail.com", party_id:21,meal_id:1)
Guest.create(first_name:"Sandy", last_name:"Moroney", email: "sandrajmoroney@comcast.net", party_id:22,meal_id:1)
Guest.create(first_name:"Tina", last_name:"Moroney", email: "christinalmoroney@gmail.com", party_id:23,meal_id:1)
Guest.create(first_name:"Katharine", last_name:"Mitropoulos", email: "", party_id:24,meal_id:1)
Guest.create(first_name:"Dimitri", last_name:"Mitropoulos", email: "", party_id:24,meal_id:1)
Guest.create(first_name:"Petra", last_name:"Mitropoulos", email: "",party_id:24,meal_id:1)
Guest.create(first_name:"Bob", last_name:"Erickson", email: "", party_id:25,meal_id:1)
Guest.create(first_name:"Joy", last_name:"Erickson", email: "", party_id:25,meal_id:1)
Guest.create(first_name:"Barbara", last_name:"Erickson", email: "berickson42@gmail.com", party_id:26,meal_id:1)
Guest.create(first_name:"Tom", last_name:"Erickson", email: "", party_id:27,meal_id:1)
Guest.create(first_name:"Sarah", last_name:"Erickson", email: "", party_id:27,meal_id:1)
Guest.create(first_name:"Christian", last_name:"Erickson",  email: "",party_id:27,meal_id:1)
Guest.create(first_name:"Matthew", last_name:"Erickson",email: "", party_id:27,meal_id:1)
Guest.create(first_name:"Allison", last_name:"Pettengill", email: "allisonkat@gmail.com", party_id:28,meal_id:1)
Guest.create(first_name:"Alex", last_name:"Pettengill", email: "losttotheart@gmail.com", party_id:28,meal_id:1)
Guest.create(first_name:"Orion", last_name:"Pettengill",email: "", party_id:28,meal_id:1)
Guest.create(first_name:"Aroussia", last_name:"Pettengill",email: "", party_id:28,meal_id:1)
Guest.create(first_name:"Bobbi", last_name:"Boyajian", email: "", party_id:29,meal_id:1)
Guest.create(first_name:"Fred", last_name:"Boyajian", email: "", party_id:29,meal_id:1)
Guest.create(first_name:"Sam", last_name:"Brewster", email: "sbrewste33@gmail.com", party_id:30,meal_id:1)
Guest.create(first_name:"Triona", last_name:"Dombroski-Fritsch", email: "tri.fritsch@gmail.com", party_id:30,meal_id:1)
Guest.create(first_name:"Abby", last_name:"Rand", email: "abbyrand28@gmail.com", party_id:31,meal_id:1)
Guest.create(first_name:"Chris", last_name:"Rand", email: "christophercrand@gmail.com", party_id:31,meal_id:1)
Guest.create(first_name:"Johanna", last_name:"Korshin", email: "johannapajak@gmail.com", party_id:32,meal_id:1)
Guest.create(first_name:"Vlad", last_name:"Korshin", email: "", party_id:32,meal_id:1)
Guest.create(first_name:"Meryl", last_name:"Ayres", email: "meryl.ayres@gmail.com", party_id:33,meal_id:1)
Guest.create(first_name:"Max", last_name:"Wall", email: "mx.wall@gmail.com", party_id:33,meal_id:1)
Guest.create(first_name:"Sander", last_name:"Doucette", email: "sanderdoucette@gmail.com", party_id:34,meal_id:1)
Guest.create(first_name:"Nancy", last_name:"Doucette", email: "nancyjmorell@gmail.com", party_id:34,meal_id:1)
Guest.create(first_name:"Winston", last_name:"Cook-Wilson", email: "winstoncookwilson@gmail.com", party_id:35,meal_id:1)
Guest.create(first_name:"Nikki", last_name:"Schilder", email: "nicoleschilder@gmail.com", party_id:35,meal_id:1)
Guest.create(first_name:"Scott", last_name:"Hanscom", email: "hottscanscom@gmail.com", party_id:36,meal_id:1)
Guest.create(first_name:"Jorie", last_name:"Schuetz", email: "", party_id:36,meal_id:1)
Guest.create(first_name:"Rebecca", last_name:"Heus", email: "rebeccaheus@gmail.com", party_id:37,meal_id:1)
Guest.create(first_name:"Emi", last_name:"Katsuta", email: "emi.katsuta@gmail.com", party_id:38,meal_id:1)
Guest.create(first_name:"Duncan", last_name:"Fraser", email: "duncan.c.fraser@gmail.com", party_id:38,meal_id:1)
Guest.create(first_name:"Julia", last_name:"Mulcrone", email: "julia.mulcrone@gmail.com", party_id:39,meal_id:1)
Guest.create(first_name:"Alex", last_name:"Hobson", email: "alexander.richard.hobson@gmail.com", party_id:39,meal_id:1)
Guest.create(first_name:"Arielle", last_name:"Cutler", email: "arielle.cutler@gmail.com", party_id:40,meal_id:1)
Guest.create(first_name:"Kate", last_name:"Sheridan", email: "m.k.sheridan.5@gmail.com", party_id:41,meal_id:1)
Guest.create(first_name:"Dave", last_name:"St. Germain", email: "", party_id:41,meal_id:1)
Guest.create(first_name:"Jenna", last_name:"Davis", email: "jenna.johnson.nyc@gmail.com", party_id:42,meal_id:1)
Guest.create(first_name:"Jed", last_name:"Davis", email: "jeremiah.edward.davis@gmail.com", party_id:42,meal_id:1)
Guest.create(first_name:"Charlotte", last_name:"Munson", email: "charlotte.e.munson@gmail.com", party_id:43,meal_id:1)
Guest.create(first_name:"Matt", last_name:"Breen", email: "", party_id:43,meal_id:1)
Guest.create(first_name:"Matt", last_name:"Gordon", email: "mdgordo@gmail.com", party_id:44,meal_id:1)
Guest.create(first_name:"Margi", last_name:"Bhatt", email: "bhattmd@gmail.com", party_id:44,meal_id:1)
Guest.create(first_name:"Joey", last_name:"Campanella", email: "josephjcamp@gmail.com", party_id:45,meal_id:1)
Guest.create(first_name:"Brett", last_name:"Morrell", email: "morrell.brett@gmail.com", party_id:46,meal_id:1)
Guest.create(first_name:"Rick", last_name:"Munschauer", email: "rmunschauer@gmail.com", party_id:47,meal_id:1)
Guest.create(first_name:"Andrea", last_name:"Gaul", email: "andrea.gaul@gmail.com", party_id:47,meal_id:1)
Guest.create(first_name:"Phil", last_name:"Tracy", email: "pdtracy@gmail.com", party_id:48,meal_id:1)
Guest.create(first_name:"Julia", last_name:"Daly", email: "julia.m.daly@gmail.com", party_id:48,meal_id:1)
Guest.create(first_name:"Mason", last_name:"Fried", email: "mason.j.fried@gmail.com", party_id:49,meal_id:1)
Guest.create(first_name:"Casey", last_name:"O'Brien", email: "", party_id:49,meal_id:1)
Guest.create(first_name:"Alexandra", last_name:"Millarhouse", email: "alexandramillar@gmail.com", party_id:50,meal_id:1)
Guest.create(first_name:"Nate", last_name:"Millarhouse", email: "nate.casa@gmail.com", party_id:50,meal_id:1)
Guest.create(first_name:"Althea", last_name:"Millarhouse",email: "", party_id:50,meal_id:1)
Guest.create(first_name:"Paulina", last_name:"Mandeville", email: "paulina.mandeville@gmail.com", party_id:51,meal_id:1)
Guest.create(first_name:"Pat", last_name:"Kelly", email: "pnkel14@gmail.com", party_id:51,meal_id:1)
Guest.create(first_name:"Blake", last_name:"Hulnick", email: "bhulnick@gmail.com", party_id:52,meal_id:1)
Guest.create(first_name:"Ann", last_name:"Shikany", email: "ann.shikany@gmail.com", party_id:52,meal_id:1)
Guest.create(first_name:"Greg", last_name:"Huffaker", email: "greghuffaker@gmail.com", party_id:53,meal_id:1)
Guest.create(first_name:"Amy", last_name:"Rumack", email: "", party_id:53,meal_id:1)
Guest.create(first_name:"Chris", last_name:"Sullivan", email: "chriscsullivan@gmail.com", party_id:54,meal_id:1)
Guest.create(first_name:"Austin", last_name:"Hawkins", email: "", party_id:54,meal_id:1)
Guest.create(first_name:"Andrew", last_name:"Shults", email: "andrewjshults@gmail.com", party_id:55,meal_id:1)
Guest.create(first_name:"Danya", last_name:"Shults", email: "danyashults@gmail.com", party_id:55,meal_id:1)
Guest.create(first_name:"Jordan", last_name:"Kisner", email: "jordan.kisner@gmail.com", party_id:56,meal_id:1)
Guest.create(first_name:"Andrew", last_name:"Haynes", email: "andrewhaynes@gmail.com", party_id:58,meal_id:1)
Guest.create(first_name:"Christine", last_name:"Haynes", email: "christinehaynes9@gmail.com", party_id:58,meal_id:1)
Guest.create(first_name:"Paul", last_name:"Haynes", email: "",party_id:58,meal_id:1)
Guest.create(first_name:"Jack", last_name:"Novak", email: "", party_id:59,meal_id:1)
Guest.create(first_name:"Megan", last_name:"Godfrey", email: "", party_id:59,meal_id:1)
Guest.create(first_name:"Christian", last_name:"Schopke", email: "", party_id:60,meal_id:1)
Guest.create(first_name:"Tone", last_name:"Schopke", email: "", party_id:60,meal_id:1)
Guest.create(first_name:"Andre", last_name:"Schopke",email: "", party_id:60,meal_id:1)
Guest.create(first_name:"Ben", last_name:"Sholl", email: "bensholl@gmail.com", party_id:61,meal_id:1)
Guest.create(first_name:"Alida", last_name:"Sholl", email: "", party_id:61,meal_id:1)
Guest.create(first_name:"Mark", last_name:"Ducommun", email: "ducommun.mark@gmail.com", party_id:62,meal_id:1)
Guest.create(first_name:"Christine", last_name:"Ducommun", email: "", party_id:62,meal_id:1)
Guest.create(first_name:"Charlie", last_name:"Palanza", email: "", party_id:63,meal_id:1)
Guest.create(first_name:"Hilary", last_name:"Palanza", email: "hilary.saverin@gmail.com", party_id:63,meal_id:1)
Guest.create(first_name:"Jack", last_name:"Scotti", email: "jack.stazie.scotti@gmail.com", party_id:64,meal_id:1)
Guest.create(first_name:"Melissa", last_name:"Scotti", email: "melissa.k.scotti@gmail.com", party_id:64,meal_id:1)
Guest.create(first_name:"Emma", last_name:"Scotti", email: "",party_id:64,meal_id:1)
Guest.create(first_name:"Will", last_name:"Welles", email: "wswelles@gmail.com", party_id:65,meal_id:1)
Guest.create(first_name:"Meghan", last_name:"Welles", email: "mcressynelson@gmail.com", party_id:65,meal_id:1)
Guest.create(first_name:"Andrew", last_name:"Whalen", email: "arwhalen@gmail.com", party_id:66,meal_id:1)
Guest.create(first_name:"Ali", last_name:"Fisher", email: "ali.fisher@gmail.com", party_id:66,meal_id:1)
Guest.create(first_name:"Nick", last_name:"Fesette", email: "nickfesette@gmail.com", party_id:67,meal_id:1)
Guest.create(first_name:"Sally", last_name:"Kral", email: "sally.kral@gmail.com", party_id:67,meal_id:1)
Guest.create(first_name:"Emma", last_name:"Racine", email: "racinemma@gmail.com", party_id:68,meal_id:1)
Guest.create(first_name:"Charlie", last_name:"Kaplan", email: "charlie.kaplan@gmail.com", party_id:68,meal_id:1)
Guest.create(first_name:"Drew", last_name:"Christ", email: "andrew.j.christ@gmail.com", party_id:69,meal_id:1)
Guest.create(first_name:"Cameron", last_name:"Breslin", email: "cameronbreslin@gmail.com", party_id:70,meal_id:1)


Meal.create(desc: "ice cream")
Meal.create(desc: "fish pie")
Meal.create(desc: "bubblegum")
Meal.create(desc: "kids meal")
Meal.create(desc: "NA")